export const demoDashboardData = {
  monthLabel: "Juin 2026",
  summary: {
    propertyCount: 3,
    activePropertiesCount: 2,
    draftPropertiesCount: 1,
    archivedPropertiesCount: 0,
    expectedRentInCents: 395000,
    collectedRentInCents: 305000,
    remainingRentInCents: 90000,
    outgoingAmountInCents: 132500,
    cashFlowInCents: 172500,
    watchPaymentsCount: 2,
    recurringExpensesCount: 4,
    availableReceiptsCount: 5,
    requestedReceiptsCount: 1,
  },
  priorityActions: [
    {
      id: "declared_paid",
      title: "Loyers declares payes",
      description:
        "Deux locataires indiquent avoir paye. Confirmez uniquement apres reception reelle.",
      value: 2,
      actionLabel: "Verifier",
      href: "/sign-up",
      tone: "warning",
    },
    {
      id: "receipt",
      title: "Quittance a generer",
      description: "Une quittance est prete a etre generee pour le mois.",
      value: 1,
      actionLabel: "Creer un compte",
      href: "/sign-up",
      tone: "info",
    },
    {
      id: "late_payment",
      title: "Paiement a surveiller",
      description: "Un loyer attendu n'est pas encore confirme comme recu.",
      value: 1,
      actionLabel: "Suivre",
      href: "/sign-up",
      tone: "danger",
    },
    {
      id: "recurring_expenses",
      title: "Depenses recurrentes",
      description:
        "Les sorties recurrentes du mois peuvent etre generees explicitement.",
      value: 3,
      actionLabel: "Generer",
      href: "/sign-up",
      tone: "success",
    },
  ],
  properties: [
    {
      id: "demo_property_lyon",
      name: "Appartement Presqu'ile",
      city: "Lyon",
      type: "T3",
      surfaceLabel: "68 m2",
      status: "Paiement OK",
      statusTone: "success",
      visualVariant: "river",
      imageSrc: "/demo/properties/appartement-lyon.png",
      expectedRentInCents: 125000,
      collectedRentInCents: 125000,
      outgoingAmountInCents: 38500,
      contractsCount: 1,
      watchPaymentsCount: 0,
      availableReceiptsCount: 2,
    },
    {
      id: "demo_property_paris",
      name: "Studio Canal Saint-Martin",
      city: "Paris",
      type: "Studio",
      surfaceLabel: "28 m2",
      status: "A surveiller",
      statusTone: "warning",
      visualVariant: "studio",
      imageSrc: "/demo/properties/studio-paris.png",
      expectedRentInCents: 90000,
      collectedRentInCents: 0,
      outgoingAmountInCents: 22000,
      contractsCount: 1,
      watchPaymentsCount: 1,
      availableReceiptsCount: 1,
    },
    {
      id: "demo_property_nantes",
      name: "Maison Saint-Felix",
      city: "Nantes",
      type: "Maison",
      surfaceLabel: "95 m2",
      status: "Actif",
      statusTone: "info",
      visualVariant: "house",
      imageSrc: "/demo/properties/maison-nantes.png",
      expectedRentInCents: 180000,
      collectedRentInCents: 180000,
      outgoingAmountInCents: 72000,
      contractsCount: 2,
      watchPaymentsCount: 0,
      availableReceiptsCount: 2,
    },
  ],
  watchPayments: [
    {
      id: "demo_payment_paris_may",
      propertyName: "Studio Canal Saint-Martin",
      city: "Paris",
      label: "Loyer juin",
      amountInCents: 90000,
      dueLabel: "Echeance depassee",
      status: "A surveiller",
    },
    {
      id: "demo_payment_lyon_charges",
      propertyName: "Appartement Presqu'ile",
      city: "Lyon",
      label: "Regularisation charges",
      amountInCents: 18000,
      dueLabel: "A verifier",
      status: "Declare paye",
    },
  ],
  recurringExpenses: [
    {
      id: "demo_recurring_loan",
      label: "Remboursement d'emprunt",
      propertyName: "Maison Saint-Felix",
      amountInCents: 69000,
    },
    {
      id: "demo_recurring_insurance",
      label: "Assurance PNO",
      propertyName: "Appartement Presqu'ile",
      amountInCents: 1800,
    },
    {
      id: "demo_recurring_condo",
      label: "Charges de copropriete",
      propertyName: "Studio Canal Saint-Martin",
      amountInCents: 9500,
    },
  ],
  expenseCategories: [
    {
      id: "demo_category_loan",
      label: "Remboursement d'emprunt",
      amountInCents: 69000,
    },
    {
      id: "demo_category_condo",
      label: "Charges de copropriete",
      amountInCents: 27500,
    },
    {
      id: "demo_category_insurance",
      label: "Assurance",
      amountInCents: 8600,
    },
    {
      id: "demo_category_works",
      label: "Travaux",
      amountInCents: 27400,
    },
  ],
  quickActions: [
    "Ajouter un logement",
    "Ajouter une depense",
    "Voir les finances",
    "Generer une quittance",
  ],
  financeActions: [
    "Ajouter une depense",
    "Ajouter une depense recurrente",
    "Generer les depenses recurrentes du mois",
    "Exporter mes finances",
  ],
  propertyActions: [
    "Ajouter un logement",
    "Voir le detail",
    "Creer un contrat",
    "Inviter un locataire",
    "Suivre les paiements",
  ],
  tenantActions: [
    "Inviter un locataire",
    "Voir les contrats",
    "Voir les logements",
    "Suivre les paiements",
  ],
  declarationActions: [
    "Verifier les revenus",
    "Completer les donnees",
    "Voir les finances",
    "Exporter mes finances",
  ],
  recentActivity: [
    {
      id: "activity_paid",
      title: "Loyer declare paye",
      description: "Appartement Presqu'ile",
      when: "Aujourd'hui",
      tone: "success",
    },
    {
      id: "activity_receipt",
      title: "Quittance disponible",
      description: "Maison Saint-Felix",
      when: "Hier",
      tone: "info",
    },
    {
      id: "activity_late",
      title: "Paiement a surveiller",
      description: "Studio Canal Saint-Martin",
      when: "Il y a 2 jours",
      tone: "warning",
    },
  ],
  tenants: {
    summary: {
      activeTenants: 3,
      pendingInvitations: 1,
      formerTenants: 1,
      contractCount: 4,
    },
    activeTenants: [
      {
        id: "demo_tenant_camille",
        name: "Camille Martin",
        email: "camille.martin@example.com",
        propertyName: "Appartement Presqu'ile",
        city: "Lyon",
        contractLabel: "Contrat individuel",
        roomLabel: null,
        status: "Actif",
        statusTone: "success",
        rentShareAmountInCents: 105000,
        chargesShareAmountInCents: 20000,
      },
      {
        id: "demo_tenant_nora",
        name: "Nora Benali",
        email: "nora.benali@example.com",
        propertyName: "Maison Saint-Felix",
        city: "Nantes",
        contractLabel: "Colocation liee",
        roomLabel: "Chambre jardin",
        status: "Actif",
        statusTone: "success",
        rentShareAmountInCents: 76000,
        chargesShareAmountInCents: 14000,
      },
      {
        id: "demo_tenant_louis",
        name: "Louis Garnier",
        email: "louis.garnier@example.com",
        propertyName: "Maison Saint-Felix",
        city: "Nantes",
        contractLabel: "Colocation liee",
        roomLabel: "Chambre etage",
        status: "Actif",
        statusTone: "success",
        rentShareAmountInCents: 78000,
        chargesShareAmountInCents: 12000,
      },
    ],
    pendingInvitations: [
      {
        id: "demo_invitation_paris",
        name: "Anais Lefevre",
        email: "anais.lefevre@example.com",
        propertyName: "Studio Canal Saint-Martin",
        city: "Paris",
        expiresLabel: "Expire dans 5 jours",
        status: "Envoyee",
        statusTone: "warning",
      },
    ],
    formerTenants: [
      {
        id: "demo_former_tenant",
        name: "Hugo Morel",
        email: "hugo.morel@example.com",
        propertyName: "Appartement Presqu'ile",
        city: "Lyon",
        endLabel: "Fin le 31 mai 2026",
        status: "Termine",
        statusTone: "muted",
      },
    ],
  },
  declarations: {
    selectedYear: 2025,
    preparedRentalIncomeInCents: 1245000,
    expensesToReviewInCents: 318000,
    paymentsIncludedCount: 14,
    paymentsNotConfirmedCount: 2,
    propertiesWithIncome: 3,
    missingData: [
      {
        id: "fiscal_type",
        title: "Type fiscal a verifier pour 3 logement(s)",
        description:
          "RentFlow ne sait pas encore si ces logements relevent d'une location nue, meublee ou d'un cas specifique.",
        tone: "warning",
      },
      {
        id: "expenses",
        title: "Depenses enregistrees a verifier",
        description:
          "Les depenses sont visibles, mais ne sont pas deduites automatiquement du montant prepare.",
        tone: "info",
      },
    ],
    propertyBreakdown: [
      {
        id: "demo_declaration_lyon",
        propertyName: "Appartement Presqu'ile",
        city: "Lyon",
        furnished: false,
        incomeInCents: 625000,
        expensesInCents: 84000,
        paymentsIncludedCount: 5,
        fiscalStatusMessage: "Non meuble dans RentFlow - fiscalite a confirmer",
      },
      {
        id: "demo_declaration_paris",
        propertyName: "Studio Canal Saint-Martin",
        city: "Paris",
        furnished: true,
        incomeInCents: 270000,
        expensesInCents: 66000,
        paymentsIncludedCount: 3,
        fiscalStatusMessage: "Meuble dans RentFlow - fiscalite a confirmer",
      },
      {
        id: "demo_declaration_nantes",
        propertyName: "Maison Saint-Felix",
        city: "Nantes",
        furnished: true,
        incomeInCents: 350000,
        expensesInCents: 168000,
        paymentsIncludedCount: 6,
        fiscalStatusMessage: "Meuble dans RentFlow - fiscalite a confirmer",
      },
    ],
    expenseCategories: [
      {
        id: "demo_tax_property_tax",
        label: "Taxe fonciere",
        amountInCents: 125000,
      },
      {
        id: "demo_tax_condo",
        label: "Charges de copropriete",
        amountInCents: 96000,
      },
      {
        id: "demo_tax_insurance",
        label: "Assurance",
        amountInCents: 42000,
      },
      {
        id: "demo_tax_works",
        label: "Travaux",
        amountInCents: 55000,
      },
    ],
    advice: [
      {
        id: "furnished",
        title: "Piste a verifier : logements marques meubles",
        description:
          "Certains logements sont marques meubles dans RentFlow. Verifiez s'ils relevent bien de la location meublee au sens fiscal.",
        tone: "info",
      },
      {
        id: "expense_ratio",
        title: "Piste a verifier : depenses importantes",
        description:
          "Les depenses enregistrees semblent significatives. Il peut etre utile de comparer votre regime fiscal avec un professionnel.",
        tone: "warning",
      },
      {
        id: "multiple_properties",
        title: "Piste a verifier : plusieurs biens",
        description:
          "Avec plusieurs biens, une organisation dediee peut etre un sujet a comparer avec un professionnel selon votre situation.",
        tone: "info",
      },
    ],
  },
};

export const demoAppData = {
  owner: {
    name: "Arthur B.",
    plan: "Pro",
    monthLabel: "Mai 2026",
    summary: {
      confirmedRentInCents: 305000,
      pendingRentInCents: 90000,
      outgoingInCents: 132500,
      cashFlowInCents: 172500,
      propertiesCount: 3,
      exportedLines: 12,
    },
    properties: [
      {
        id: "canal",
        name: "Appartement Canal",
        city: "Paris",
        address: "18 quai de Valmy",
        type: "T2 meuble",
        surface: "43 m2",
        status: "Actif",
        statusTone: "success",
        imageSrc: "/demo/properties/studio-paris.png",
        rentInCents: 125000,
        chargesInCents: 18000,
        fiscalType: "Meuble",
        contracts: 1,
        paymentsToReview: 1,
        receiptsReady: 2,
      },
      {
        id: "republique",
        name: "Studio Republique",
        city: "Lyon",
        address: "9 rue de la Republique",
        type: "Studio",
        surface: "28 m2",
        status: "A surveiller",
        statusTone: "warning",
        imageSrc: "/demo/properties/appartement-lyon.png",
        rentInCents: 90000,
        chargesInCents: 9000,
        fiscalType: "Nu",
        contracts: 1,
        paymentsToReview: 1,
        receiptsReady: 1,
      },
      {
        id: "pins",
        name: "Maison des Pins",
        city: "Annecy",
        address: "4 allee des Pins",
        type: "Maison",
        surface: "95 m2",
        status: "Complet",
        statusTone: "info",
        imageSrc: "/demo/properties/maison-nantes.png",
        rentInCents: 180000,
        chargesInCents: 24000,
        fiscalType: "Meuble",
        contracts: 2,
        paymentsToReview: 0,
        receiptsReady: 2,
      },
    ],
    tenants: [
      {
        id: "lea",
        name: "Lea Martin",
        email: "lea.martin@example.test",
        propertyName: "Appartement Canal",
        city: "Paris",
        status: "Actif",
        statusTone: "success",
        rentInCents: 125000,
        requestTitle: "Document pour dossier CAF",
        requestCategory: "Document",
      },
      {
        id: "hugo",
        name: "Hugo Bernard",
        email: "hugo.bernard@example.test",
        propertyName: "Studio Republique",
        city: "Lyon",
        status: "Invitation envoyee",
        statusTone: "warning",
        rentInCents: 90000,
        requestTitle: "Question sur le paiement",
        requestCategory: "Paiement",
      },
      {
        id: "camille",
        name: "Camille Moreau",
        email: "camille.moreau@example.test",
        propertyName: "Maison des Pins",
        city: "Annecy",
        status: "Actif",
        statusTone: "success",
        rentInCents: 102000,
        requestTitle: "Reparation volet salon",
        requestCategory: "Travaux",
      },
    ],
    payments: [
      {
        id: "payment-confirmed",
        label: "Loyer mai",
        propertyName: "Appartement Canal",
        tenantName: "Lea Martin",
        dueDate: "05/05/2026",
        amountInCents: 125000,
        status: "Confirme recu",
        statusTone: "success",
        kind: "Loyer confirme",
      },
      {
        id: "payment-declared",
        label: "Loyer mai",
        propertyName: "Studio Republique",
        tenantName: "Hugo Bernard",
        dueDate: "05/05/2026",
        amountInCents: 90000,
        status: "Declare paye",
        statusTone: "warning",
        kind: "A confirmer",
      },
      {
        id: "payment-planned",
        label: "Loyer juin",
        propertyName: "Maison des Pins",
        tenantName: "Camille Moreau",
        dueDate: "05/06/2026",
        amountInCents: 102000,
        status: "Prevu",
        statusTone: "info",
        kind: "Paiement prevu",
      },
      {
        id: "payment-late",
        label: "Loyer avril",
        propertyName: "Studio Republique",
        tenantName: "Hugo Bernard",
        dueDate: "05/04/2026",
        amountInCents: 90000,
        status: "Retard fictif",
        statusTone: "danger",
        kind: "A surveiller",
      },
    ],
    receipts: [
      {
        id: "receipt-requested",
        propertyName: "Studio Republique",
        tenantName: "Hugo Bernard",
        month: "Mai 2026",
        status: "Demandee",
        statusTone: "warning",
      },
      {
        id: "receipt-generated",
        propertyName: "Appartement Canal",
        tenantName: "Lea Martin",
        month: "Mai 2026",
        status: "Generee",
        statusTone: "success",
      },
      {
        id: "receipt-sent",
        propertyName: "Maison des Pins",
        tenantName: "Camille Moreau",
        month: "Avril 2026",
        status: "Disponible",
        statusTone: "info",
      },
    ],
    tenantRequests: [
      {
        id: "repair",
        title: "Reparation volet salon",
        category: "Travaux / reparation",
        tenantName: "Camille Moreau",
        propertyName: "Maison des Pins",
        status: "Ouverte",
        statusTone: "warning",
      },
      {
        id: "document",
        title: "Document pour dossier CAF",
        category: "Document",
        tenantName: "Lea Martin",
        propertyName: "Appartement Canal",
        status: "A traiter",
        statusTone: "info",
      },
      {
        id: "payment-question",
        title: "Question sur le paiement",
        category: "Paiement",
        tenantName: "Hugo Bernard",
        propertyName: "Studio Republique",
        status: "Ouverte",
        statusTone: "warning",
      },
    ],
    expenses: [
      {
        id: "loan",
        category: "Emprunt",
        label: "Echeance declarative",
        amountInCents: 69000,
      },
      {
        id: "insurance",
        category: "Assurance",
        label: "Assurance PNO",
        amountInCents: 8600,
      },
      {
        id: "condo",
        category: "Copropriete",
        label: "Charges copropriete",
        amountInCents: 27500,
      },
      {
        id: "works",
        category: "Travaux",
        label: "Intervention plomberie",
        amountInCents: 27400,
      },
    ],
    declarations: {
      year: 2025,
      preparedIncomeInCents: 1245000,
      missingItems: ["Type fiscal a verifier pour 2 logements"],
      advice: [
        "Verifier le regime nu ou meuble pour chaque logement.",
        "Comparer les depenses connues avec vos justificatifs.",
        "Faire relire avant toute declaration officielle.",
      ],
    },
    recentActivity: [
      "Loyer confirme pour Appartement Canal",
      "Quittance generee pour Lea Martin",
      "Demande locataire traitee",
    ],
  },
  tenant: {
    name: "Lea Martin",
    ownerName: "Arthur B.",
    property: {
      name: "Appartement Canal",
      city: "Paris",
      address: "18 quai de Valmy",
      type: "T2 meuble",
      status: "Actif",
      statusTone: "success",
      imageSrc: "/demo/properties/studio-paris.png",
    },
    contract: {
      id: "contract-canal",
      type: "Bail habitation meuble",
      status: "Actif",
      startDate: "01/03/2026",
      endDate: "28/02/2027",
      paymentDay: 5,
      rentInCents: 86000,
      chargesInCents: 12000,
      depositInCents: 86000,
      currency: "EUR",
    },
    actions: [
      {
        id: "declare-paid",
        title: "Declarer un loyer paye",
        description: "Action visible 1 jour avant l'echeance.",
        tone: "warning",
      },
      {
        id: "receipt-seen",
        title: "Quittance disponible",
        description: "La quittance reste dans l'historique apres lecture.",
        tone: "info",
      },
      {
        id: "request-done",
        title: "Demande proprietaire traitee",
        description: "Confirmez que la reponse vous convient.",
        tone: "success",
      },
    ],
    payments: [
      {
        id: "rent-june",
        label: "Loyer juin",
        amountInCents: 98000,
        status: "A declarer",
        tone: "warning",
      },
      {
        id: "rent-may",
        label: "Loyer mai",
        amountInCents: 98000,
        status: "Confirme",
        tone: "success",
      },
      {
        id: "rent-april",
        label: "Loyer avril",
        amountInCents: 98000,
        status: "Quittance disponible",
        tone: "info",
      },
    ],
    receipts: [
      {
        id: "receipt-may",
        month: "Mai 2026",
        status: "Disponible",
        tone: "success",
      },
      {
        id: "receipt-april",
        month: "Avril 2026",
        status: "Consultee",
        tone: "muted",
      },
    ],
    requests: [
      {
        id: "request-doc",
        title: "Attestation d'occupation",
        category: "Document",
        status: "Traitee par le proprietaire",
        tone: "success",
      },
      {
        id: "request-repair",
        title: "Joint de fenetre a verifier",
        category: "Travaux / reparation",
        status: "Ouverte",
        tone: "warning",
      },
    ],
    formerContract: {
      propertyName: "Studio Republique",
      city: "Lyon",
      endDate: "31/12/2025",
    },
  },
} as const;
