export const demoDashboardData = {
  monthLabel: "Juin 2026",
  summary: {
    propertyCount: 3,
    activePropertiesCount: 2,
    draftPropertiesCount: 1,
    archivedPropertiesCount: 0,
    expectedRentInCents: 395000,
    collectedRentInCents: 305000,
    remainingRentInCents: 90000,
    outgoingAmountInCents: 132500,
    cashFlowInCents: 172500,
    watchPaymentsCount: 2,
    recurringExpensesCount: 4,
    availableReceiptsCount: 5,
    requestedReceiptsCount: 1,
  },
  priorityActions: [
    {
      id: "declared_paid",
      title: "Loyers declares payes",
      description:
        "Deux locataires indiquent avoir paye. Confirmez uniquement apres reception reelle.",
      value: 2,
      actionLabel: "Verifier",
      href: "/sign-up",
      tone: "warning",
    },
    {
      id: "receipt",
      title: "Quittance a generer",
      description: "Une quittance est prete a etre generee pour le mois.",
      value: 1,
      actionLabel: "Creer un compte",
      href: "/sign-up",
      tone: "info",
    },
    {
      id: "late_payment",
      title: "Paiement a surveiller",
      description: "Un loyer attendu n'est pas encore confirme comme recu.",
      value: 1,
      actionLabel: "Suivre",
      href: "/sign-up",
      tone: "danger",
    },
    {
      id: "recurring_expenses",
      title: "Depenses recurrentes",
      description:
        "Les sorties recurrentes du mois peuvent etre generees explicitement.",
      value: 3,
      actionLabel: "Generer",
      href: "/sign-up",
      tone: "success",
    },
  ],
  properties: [
    {
      id: "demo_property_lyon",
      name: "Appartement Presqu'ile",
      city: "Lyon",
      type: "T3",
      surfaceLabel: "68 m2",
      status: "Paiement OK",
      statusTone: "success",
      visualVariant: "river",
      imageSrc: "/demo/properties/appartement-lyon.png",
      expectedRentInCents: 125000,
      collectedRentInCents: 125000,
      outgoingAmountInCents: 38500,
      contractsCount: 1,
      watchPaymentsCount: 0,
      availableReceiptsCount: 2,
    },
    {
      id: "demo_property_paris",
      name: "Studio Canal Saint-Martin",
      city: "Paris",
      type: "Studio",
      surfaceLabel: "28 m2",
      status: "A surveiller",
      statusTone: "warning",
      visualVariant: "studio",
      imageSrc: "/demo/properties/studio-paris.png",
      expectedRentInCents: 90000,
      collectedRentInCents: 0,
      outgoingAmountInCents: 22000,
      contractsCount: 1,
      watchPaymentsCount: 1,
      availableReceiptsCount: 1,
    },
    {
      id: "demo_property_nantes",
      name: "Maison Saint-Felix",
      city: "Nantes",
      type: "Maison",
      surfaceLabel: "95 m2",
      status: "Actif",
      statusTone: "info",
      visualVariant: "house",
      imageSrc: "/demo/properties/maison-nantes.png",
      expectedRentInCents: 180000,
      collectedRentInCents: 180000,
      outgoingAmountInCents: 72000,
      contractsCount: 2,
      watchPaymentsCount: 0,
      availableReceiptsCount: 2,
    },
  ],
  watchPayments: [
    {
      id: "demo_payment_paris_may",
      propertyName: "Studio Canal Saint-Martin",
      city: "Paris",
      label: "Loyer juin",
      amountInCents: 90000,
      dueLabel: "Echeance depassee",
      status: "A surveiller",
    },
    {
      id: "demo_payment_lyon_charges",
      propertyName: "Appartement Presqu'ile",
      city: "Lyon",
      label: "Regularisation charges",
      amountInCents: 18000,
      dueLabel: "A verifier",
      status: "Declare paye",
    },
  ],
  recurringExpenses: [
    {
      id: "demo_recurring_loan",
      label: "Remboursement d'emprunt",
      propertyName: "Maison Saint-Felix",
      amountInCents: 69000,
    },
    {
      id: "demo_recurring_insurance",
      label: "Assurance PNO",
      propertyName: "Appartement Presqu'ile",
      amountInCents: 1800,
    },
    {
      id: "demo_recurring_condo",
      label: "Charges de copropriete",
      propertyName: "Studio Canal Saint-Martin",
      amountInCents: 9500,
    },
  ],
  expenseCategories: [
    {
      id: "demo_category_loan",
      label: "Remboursement d'emprunt",
      amountInCents: 69000,
    },
    {
      id: "demo_category_condo",
      label: "Charges de copropriete",
      amountInCents: 27500,
    },
    {
      id: "demo_category_insurance",
      label: "Assurance",
      amountInCents: 8600,
    },
    {
      id: "demo_category_works",
      label: "Travaux",
      amountInCents: 27400,
    },
  ],
  quickActions: [
    "Ajouter un logement",
    "Ajouter une depense",
    "Voir les finances",
    "Generer une quittance",
  ],
  financeActions: [
    "Ajouter une depense",
    "Ajouter une depense recurrente",
    "Generer les depenses recurrentes du mois",
    "Exporter mes finances",
  ],
  propertyActions: [
    "Ajouter un logement",
    "Voir le detail",
    "Creer un contrat",
    "Inviter un locataire",
    "Suivre les paiements",
  ],
  tenantActions: [
    "Inviter un locataire",
    "Voir les contrats",
    "Voir les logements",
    "Suivre les paiements",
  ],
  declarationActions: [
    "Verifier les revenus",
    "Completer les donnees",
    "Voir les finances",
    "Exporter mes finances",
  ],
  recentActivity: [
    {
      id: "activity_paid",
      title: "Loyer declare paye",
      description: "Appartement Presqu'ile",
      when: "Aujourd'hui",
      tone: "success",
    },
    {
      id: "activity_receipt",
      title: "Quittance disponible",
      description: "Maison Saint-Felix",
      when: "Hier",
      tone: "info",
    },
    {
      id: "activity_late",
      title: "Paiement a surveiller",
      description: "Studio Canal Saint-Martin",
      when: "Il y a 2 jours",
      tone: "warning",
    },
  ],
  tenants: {
    summary: {
      activeTenants: 3,
      pendingInvitations: 1,
      formerTenants: 1,
      contractCount: 4,
    },
    activeTenants: [
      {
        id: "demo_tenant_camille",
        name: "Camille Martin",
        email: "camille.martin@example.com",
        propertyName: "Appartement Presqu'ile",
        city: "Lyon",
        contractLabel: "Contrat individuel",
        roomLabel: null,
        status: "Actif",
        statusTone: "success",
        rentShareAmountInCents: 105000,
        chargesShareAmountInCents: 20000,
      },
      {
        id: "demo_tenant_nora",
        name: "Nora Benali",
        email: "nora.benali@example.com",
        propertyName: "Maison Saint-Felix",
        city: "Nantes",
        contractLabel: "Colocation liee",
        roomLabel: "Chambre jardin",
        status: "Actif",
        statusTone: "success",
        rentShareAmountInCents: 76000,
        chargesShareAmountInCents: 14000,
      },
      {
        id: "demo_tenant_louis",
        name: "Louis Garnier",
        email: "louis.garnier@example.com",
        propertyName: "Maison Saint-Felix",
        city: "Nantes",
        contractLabel: "Colocation liee",
        roomLabel: "Chambre etage",
        status: "Actif",
        statusTone: "success",
        rentShareAmountInCents: 78000,
        chargesShareAmountInCents: 12000,
      },
    ],
    pendingInvitations: [
      {
        id: "demo_invitation_paris",
        name: "Anais Lefevre",
        email: "anais.lefevre@example.com",
        propertyName: "Studio Canal Saint-Martin",
        city: "Paris",
        expiresLabel: "Expire dans 5 jours",
        status: "Envoyee",
        statusTone: "warning",
      },
    ],
    formerTenants: [
      {
        id: "demo_former_tenant",
        name: "Hugo Morel",
        email: "hugo.morel@example.com",
        propertyName: "Appartement Presqu'ile",
        city: "Lyon",
        endLabel: "Fin le 31 mai 2026",
        status: "Termine",
        statusTone: "muted",
      },
    ],
  },
  declarations: {
    selectedYear: 2025,
    preparedRentalIncomeInCents: 1245000,
    expensesToReviewInCents: 318000,
    paymentsIncludedCount: 14,
    paymentsNotConfirmedCount: 2,
    propertiesWithIncome: 3,
    missingData: [
      {
        id: "fiscal_type",
        title: "Type fiscal a verifier pour 3 logement(s)",
        description:
          "RentFlow ne sait pas encore si ces logements relevent d'une location nue, meublee ou d'un cas specifique.",
        tone: "warning",
      },
      {
        id: "expenses",
        title: "Depenses enregistrees a verifier",
        description:
          "Les depenses sont visibles, mais ne sont pas deduites automatiquement du montant prepare.",
        tone: "info",
      },
    ],
    propertyBreakdown: [
      {
        id: "demo_declaration_lyon",
        propertyName: "Appartement Presqu'ile",
        city: "Lyon",
        furnished: false,
        incomeInCents: 625000,
        expensesInCents: 84000,
        paymentsIncludedCount: 5,
        fiscalStatusMessage: "Non meuble dans RentFlow - fiscalite a confirmer",
      },
      {
        id: "demo_declaration_paris",
        propertyName: "Studio Canal Saint-Martin",
        city: "Paris",
        furnished: true,
        incomeInCents: 270000,
        expensesInCents: 66000,
        paymentsIncludedCount: 3,
        fiscalStatusMessage: "Meuble dans RentFlow - fiscalite a confirmer",
      },
      {
        id: "demo_declaration_nantes",
        propertyName: "Maison Saint-Felix",
        city: "Nantes",
        furnished: true,
        incomeInCents: 350000,
        expensesInCents: 168000,
        paymentsIncludedCount: 6,
        fiscalStatusMessage: "Meuble dans RentFlow - fiscalite a confirmer",
      },
    ],
    expenseCategories: [
      {
        id: "demo_tax_property_tax",
        label: "Taxe fonciere",
        amountInCents: 125000,
      },
      {
        id: "demo_tax_condo",
        label: "Charges de copropriete",
        amountInCents: 96000,
      },
      {
        id: "demo_tax_insurance",
        label: "Assurance",
        amountInCents: 42000,
      },
      {
        id: "demo_tax_works",
        label: "Travaux",
        amountInCents: 55000,
      },
    ],
    advice: [
      {
        id: "furnished",
        title: "Piste a verifier : logements marques meubles",
        description:
          "Certains logements sont marques meubles dans RentFlow. Verifiez s'ils relevent bien de la location meublee au sens fiscal.",
        tone: "info",
      },
      {
        id: "expense_ratio",
        title: "Piste a verifier : depenses importantes",
        description:
          "Les depenses enregistrees semblent significatives. Il peut etre utile de comparer votre regime fiscal avec un professionnel.",
        tone: "warning",
      },
      {
        id: "multiple_properties",
        title: "Piste a verifier : plusieurs biens",
        description:
          "Avec plusieurs biens, une organisation dediee peut etre un sujet a comparer avec un professionnel selon votre situation.",
        tone: "info",
      },
    ],
  },
};
